---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: StrimziAdmin
rules:
- apiGroups:
  - "kafka.strimzi.io"
  resources:
  - kafkas
  - kafkaconnects
  - kafkaconnects2is
  - kafkausers
  - kafkatopics
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: StrimziAdminBinding
subjects:
  - kind: User
    name: system:serviceaccount:00odh:opendatahub-operator
  - kind: User
    name: opentlc-mgr
roleRef:
  kind: ClusterRole
  name: StrimziAdmin
  apiGroup: rbac.authorization.k8s.io